### ISSUE TITLE
An issue!

### ISSUE THREAD

**Issue by taylorsilva** [taylorsilva/test#1]
This is an issue where some problem is being described.

**Comment by taylorsilva** [comment]
some discussion..... okay we'll fix it!

**Comment by taylorsilva** [comment]
# Issue Status
###### Keep editing this comment with the current status of the issue

***

### Summary
###### Keep this high-level. Only the most important details.

The thing is broken and we need to fix it. You can find

***

### Task List

- [X] Write some tests to ensure problem duck doesn't happen again
- [ ] Implement the fix
- [ ] Add a task in CI to run the test
- [ ] ~~Redeploy the world~~
- [ ] Update the docs

***

### Next Steps
###### What needs to be done next to move this story forward?

We started implementing the fix. The latest changes are on this branch: https://github.com/taylorsilva/test/tree/some-branch

**Comment by taylorsilva** [comment]
### Day 1 - Dev Notes

Manually reproduced the issue. Was very tricky to reproduce.

Next Steps: Write a test that reproduces the issue for us.

**Comment by taylorsilva** [comment]
### Day 2 - Dev Notes

Finished writing the test and was able to start implementing a solution. Our work is on `some-branch`.
